import wine from '../assets/img/wine.png';

const wineData = [
    {
        id: 1,
        name: "Rượu Vang Đỏ 1",
        origin: "Pháp",
        alcoholContent: "14%",
        price: "$20",
        image: wine,
    },
    {
        id: 2,
        name: "Rượu Vang Trắng B2",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 3,
        name: "Rượu Vang Trắng B3",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 4,
        name: "Rượu Vang Trắng B4",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 5,
        name: "Rượu Vang Trắng B5",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 6,
        name: "Rượu Vang Trắng B6",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 7,
        name: "Rượu Vang Trắng B7",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 8,
        name: "Rượu Vang Trắng B8",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 9,
        name: "Rượu Vang Trắng B9",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 10,
        name: "Rượu Vang Trắng 10",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 11,
        name: "Rượu Vang Trắng 11",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 12,
        name: "Rượu Vang Trắng 12",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 13,
        name: "Rượu Vang Trắng 13",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 14,
        name: "Rượu Vang Trắng 14",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 15,
        name: "Rượu Vang Trắng 15",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 16,
        name: "Rượu Vang Trắng 16",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 17,
        name: "Rượu Vang Trắng 17",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 18,
        name: "Rượu Vang Trắng 18",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 19,
        name: "Rượu Vang Trắng B19",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 20,
        name: "Rượu Vang Trắng20",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 21,
        name: "Rượu Vang Trắng 21",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 22,
        name: "Rượu Vang Trắng 22",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
    {
        id: 23,
        name: "Rượu Vang Trắng 23",
        origin: "Ý",
        alcoholContent: "12%",
        price: "$25",
        image: wine,
    },
];
export default wineData;